name: pipeline

on:
  push:

defaults:
  run:
    shell: bash

jobs:
  test:
    runs-on: ubuntu-20.04
    container: golang:1.18-bullseye

    steps:
      - uses: actions/checkout@v2
      - name: Setup Go environment
        run: |
          go mod download && go mod verify

      - name: go test
        run: |
          go test ./...

      - name: go vet
        run: "go vet ./..."

      - name: go staticcheck
        uses: dominikh/staticcheck-action@v1.1.0
        with:
          version: "2022.1.1"
          min-go-version: "1.18"
          install-go: false